"use server";

import { getServerSession } from "next-auth";
import { authOptions } from "@app/api/auth/[...nextauth]/route";
import { PrismaClient } from "@prisma/client";
import { revalidatePath } from "next/cache";
async function createCollection(formdata, files) {
  try {
    const prisma = new PrismaClient();
    const session = await getServerSession(authOptions);
    const uid = session?.user.id;

    const collectionName = formdata.get("collectionName");

    const aperture = formdata.getAll("aperture");
    const shutterspeed = formdata.getAll("shutterspeed");
    const iso = formdata.getAll("iso");
    // Interactive transaction
    await prisma.$transaction(async (prisma) => {
      let collection = await prisma.collection.create(
        {
          data: {
            name: collectionName,
            uid,
            photos: {
              create: files.map((file) => ({
                name: file.name,
                uid,
                aperture: parseFloat(aperture[file.idx]),
                shutterspeed: shutterspeed[file.idx],
                iso: parseInt(iso[file.idx]),
                pid: file.fileId, // generated by b2
              })),
            },
          },
          include: { photos: true },
        },
        { timeout: 10000 }
      );
      collection = await prisma.collection.update({
        where: {
          cid: collection.cid,
        },
        data: {
          thumbnail: {
            connect: {
              pid: collection.photos[0].pid,
            },
          },
        },
      });
    });

    revalidatePath("/");
    return { status: 200 };
  } catch (err) {
    console.log(err);
    return { status: 500 };
  }
}

export default createCollection;
